# Generated by Django 4.1.1 on 2022-10-08 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("num", models.AutoField(primary_key=True, serialize=False)),
                ("nickname", models.CharField(max_length=50)),
                ("contents", models.CharField(max_length=200)),
                ("time", models.DateTimeField()),
                ("recommendation", models.PositiveIntegerField(default=0)),
                ("pw", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="MyUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userid", models.CharField(max_length=50)),
                ("pw", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("nickname", models.CharField(max_length=50)),
                ("admin", models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("num", models.AutoField(primary_key=True, serialize=False)),
                ("nickname", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=100)),
                ("contents", models.CharField(max_length=500)),
                ("time", models.DateTimeField()),
                ("views", models.PositiveIntegerField(default=0)),
                ("recommendation", models.PositiveIntegerField(default=0)),
                ("category", models.CharField(max_length=20)),
                ("pw", models.CharField(max_length=50)),
                ("notice", models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="PostRecommend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.CharField(default="", max_length=20)),
                ("nickname", models.CharField(max_length=50)),
                (
                    "reply",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="post.post"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommentRecommend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.CharField(default="", max_length=20)),
                ("nickname", models.CharField(max_length=50)),
                (
                    "reply",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="post.comment"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="comment",
            name="reply",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="post.post"
            ),
        ),
    ]
